require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false

# ドキュメンテーションコメントの警告を無効化（開発中は不要）
Style/Documentation:
  Enabled: false

# メソッド・ブロックの長さ制限を緩和
Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 35

# テストファイルのブロック長制限を緩和
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
